version: '3'
services:
  server:
    build:
      context: .
    ports:
      - "8010:8010"
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_REPORTING_DISABLED: "false"
    #volumes:
      # Data persistence
      # sudo mkdir -p /srv/docker/influxdb/data
      #- /srv/docker/influxdb/data:/var/lib/influxdb

  telegraf:
    image: telegraf:1.8
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - server

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    #volumes:
      # Data persistence
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      #- /srv/docker/grafana/data:/var/lib/grafana
